### ISSUE TITLE
Webhook: use button for reply

### ISSUE THREAD

**Issue by ascpial** [Gunivers/Gipsy-plugins#27]
Utiliser un lien plutôt qu'un embed pour la réponse (voir screenshots)
Ça permettra de ne pas casser les embeds (comme tenor par exemple) lorsque le message est une réponse.

![image](https://user-images.githubusercontent.com/72463129/210793253-5b37bd79-4899-4277-ae7f-f911dde4f01d.png)
![image](https://user-images.githubusercontent.com/72463129/210793370-fba49185-55c5-4bdd-b407-7b9f00bae53e.png)

**Comment by ZRunner** [comment]
Je ne pense pas que ça soit une bonne idée, la solution actuelle permet de rapidement savoir à quel message précédent la réponse fait référence, sans avoir à cliquer toutes les 2s. Sans compter le client mobile (en tout cas sur mon tel) qui ne redirige pas vers le message s’il est visible à l’écran (donc impossible de savoir lequel des 10 derniers messages ça correspond). 
J’aime l’esthétique et je comprend l’utilité, mais ce serait une perte de fonctionnalités selon moi
