### ISSUE TITLE
Error when editing wormhole name with no webhook name provided

### ISSUE THREAD

**Issue by LeiRoF** [Gunivers/Gipsy-plugins#5]
![image](https://user-images.githubusercontent.com/12165342/196001232-5da45902-3712-4bed-b093-95ac60238aba.png)

**Comment by VForiel** [comment]
More or less fixed here (not able to reproduce the bug but the error message is improved and will now indicate to the user the correct syntax):
https://github.com/Gunivers/Gipsy/pull/69/commits/3b34b0ac276f176c494d7952103741495c53ddd0
