### ISSUE TITLE
Error in `!group join` command

### ISSUE THREAD

**Issue by LeiRoF** [Gunivers/Gipsy-plugins#6]
![image](https://user-images.githubusercontent.com/12165342/196023147-340e641f-e442-4e85-9537-0fa47edd80c5.png)

Note: The group doesn't exist

![image](https://user-images.githubusercontent.com/12165342/196019843-fab691a6-8cd7-4bec-a78c-f216ad9c8478.png)

**Comment by VForiel** [comment]
Fixed here: https://github.com/Gunivers/Gipsy-plugins/pull/9/commits/687e0213201177cff101c905b618a2bb23a46893
